# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: 'uni-docker-hub'
      repository: 'abdelhakachourhorizon/azp-test'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(tag)'
  - task: trivy@1
    inputs:
      version: 'latest'
      image: 'abdelhakachourhorizon/azp-test:$(tag)'
      severities: 'CRITICAL'